version: '3.8'

services:
  aws-trivia-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aws-trivia-api.rule=Host(`api.your-domain.com`)"
      - "traefik.http.routers.aws-trivia-api.tls=true"
      - "traefik.http.routers.aws-trivia-api.tls.certresolver=letsencrypt"

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - aws-trivia-api
    restart: unless-stopped

  # Optional: Redis for caching (future enhancement)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
